version: '3'
services:
  app:
    build: .
    ports:
      - "5000:5001"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=netquest_assignment
      - POSTGRES_HOST=db
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=netquest_assignment
    ports:
      - "5433:5433"